-
  name: 'Execute apt update and apt upgrade on target system(s)-localhost'
  hosts: lts
  #hosts: U643
  #hosts: controller
  #hosts: all
  become: yes
  tasks:

    - name: Running "apt-get upgrade"    
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
      when: ansible_os_family == 'Debian'

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
