---
- import_playbook: playbook_1_init_system_configuration.yml
- import_playbook: playbook_2_add_and_install_from_kali_repos.yml
- import_playbook: playbook_61_keyed_user_creation.yml
- import_playbook: playbook_62_ssh_hardening.yml
- import_playbook: playbook_65_apt_upgrade.yml

...
