---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: localhost

  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Creating user(s) with random credentials
      become: true
      user:
        name: "{{ item.1 }}"
        comment: "{{ item.1 | title }} {{ item.0.surname }}"
        # https://docs.ansible.com/ansible/latest/plugins/lookup/password.html
        password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits,punctuation') | password_hash('sha512') }}"
      with_subelements:
        -
          - surname: Smith
            members:
              - james
              - hayley
              - lily
              - anwen
          - surname: Jones
            members:
              - freya
              - mike
              - jason
          - surname: Johnson
            members:
              - ana
              - chris
          - surname: Brown
            members:
              - jessica
          - surname: Miller
            members:
              - sara
              - alex
              - mary
              - bob
              - lee
        - members

#  referenced:::::
#   ansible@ubuntu-c:~/diveintoansible/Ansible Playbooks, Deep Dive/Looping/11$
# Three dots indicate the end of a YAML document
...
