---
- hosts: all
  become: true

  tasks:
    # User account configuration.
    - name: Add a deployment user.
      user:
        name: ansi
        shell: /bin/bash
        state: present

    # Disable root login and use `sudo`.
    - name: Add sudo rights for deployment user.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^ansi'
        line: 'ansi ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: Create authorized key
      authorized_key:
        # user: "{{ ansible_env.USER }}"  #copies the key to the user being connected to by ansible
        user: ansi
        key: "{{ item }}"
        validate_certs: false
      with_file:
        # - /home/ansible/.ssh/id_rsa.pub
        # - custom_key.pub
        - "{{ lookup('env','HOME') + '/.ssh/custom_ansi.pub' }}"
        - "{{ lookup('env','HOME') + '/.ssh/id_ly4e_github.pub' }}"
        # - https://github.com/ly4e.keys

### referenced::: https://github.com/geerlingguy/ansible-for-devops/blob/master/security/main.yml
### for inspiration and direction
...
