---
-
  name: 'Execute apt update and apt upgrade on target system(s)'
  hosts: all
  become: true
  tasks:

    - name: Running "apt-get upgrade"
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true
      when: ansible_os_family == 'Debian'

    - name: Remove useless packages from the cache
      apt:
        autoclean: true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: true
