---
- name: 'Execute apt update and apt upgrade on target system(s)'
  hosts: all
  become: true

  tasks:
    - name: Running "apt upgrade and cleanup"
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true
        # Remove useless packages from the cache
        autoclean: true
        # Remove dependencies that are no longer required
        autoremove: true
      when: ansible_os_family == 'Debian'

...
