---
- hosts: all
  become: true

  tasks:
    # User account configuration.
    - name: Add a deployment user.
      user:
        name: ansi
        shell: /bin/bash
        state: present

    - name: Add sudo rights for deployment user.
      lineinfile:
        dest: /etc/sudoers
        regexp: '^ansi'
        line: 'ansi ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: Create authorized key
      authorized_key:
        # user: "{{ ansible_env.USER }}"  #copies the key to the user being connected to by ansible
        user: ansi
        key: "{{ item }}"
        validate_certs: false
      with_file:
        # - /home/ansible/.ssh/id_rsa.pub
        # - custom_key.pub
        - "{{ lookup('env','HOME') + '/.ssh/custom_ansi.pub' }}"
        - "{{ lookup('env','HOME') + '/.ssh/id_ly4e_github.pub' }}"

    # User account configuration.
    - name: ensure second user - bkm
      user:
        name: bkm
        shell: /bin/bash
        state: present

    - name: Add sudo rights for bkm user
      lineinfile:
        dest: /etc/sudoers
        regexp: '^bkm'
        line: 'bkm ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: load authorized key - bkm
      authorized_key:
        user: bkm
        # key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEcSd0/ZEyNcZDhDjE9HLLrc8PYNidzav3ChTlgwRrjp id_ly4e_github" 
        key: https://github.com/ly4e.keys
        validate_certs: false
        state: present

### referenced::: https://github.com/geerlingguy/ansible-for-devops/blob/master/security/main.yml
### for inspiration and direction
...
